# -*- coding: utf-8 -*-
"""Cloudflare D1 alias mailbox helper (optional email backend)."""

from .alias_mail import (  # noqa: F401
    ALLOWED_DOMAINS,
    API_BASE,
    CF,
    DOMAINS,
    EXTRA_DOMAINS,
    create_alias,
    decode_mime_header,
    decode_raw,
    domain_mail_rows,
    env_token,
    extract_code,
    healthy_domains,
    latest_code,
    latest_domain_mails,
    list_aliases,
    list_mails,
    load_health,
    load_state,
    main,
    next_rotating_domain,
    normalize_address,
    parse_mail_row,
    pick_domain,
    random_local,
    reset_rotating_domain,
    save_health,
    save_state,
    set_domain_health,
)

__all__ = [
    "ALLOWED_DOMAINS",
    "API_BASE",
    "CF",
    "DOMAINS",
    "EXTRA_DOMAINS",
    "create_alias",
    "decode_mime_header",
    "decode_raw",
    "domain_mail_rows",
    "env_token",
    "extract_code",
    "healthy_domains",
    "latest_code",
    "latest_domain_mails",
    "list_aliases",
    "list_mails",
    "load_health",
    "load_state",
    "main",
    "next_rotating_domain",
    "normalize_address",
    "parse_mail_row",
    "pick_domain",
    "random_local",
    "reset_rotating_domain",
    "save_health",
    "save_state",
    "set_domain_health",
]
